/**
 * Ravimoshark Contract API
 * This is an API to interact with Ravimoshark contracts database. # Introduction This API allow to create, modify and delete contracts and machines. It also interacts with machines imported from SAGE database. # User Authentication This API does not contain any kind of user validation but It request to have a valid authentication user to interact with it. For more information about user Authentication, please refer to [Ravimoshark User Authentication](https://ravimoshark.com/back/apis/auth/latest). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: dev@ravimoshark.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { Clients } from './clients';
import { ImportedMachines } from './importedMachines';
import { Locations } from './locations';


/**
 * Client's contract.
 */
export interface Contracts { 
    refContract?: number;
    locations?: Array<Locations>;
    idLocations?: Array<number>;
    importedMachines?: Array<ImportedMachines>;
    idImportedMachines?: Array<number>;
    refClient?: string;
    client?: Clients;
    identification?: string;
    dateDebut?: string;
    dateFin?: string;
    reconduction?: string;
    loyer?: number;
    miniconso?: number;
    reviewed?: boolean;
    valid?: boolean;
    createdAt?: string;
    updatedAt?: string;
    deleted?: boolean;
}